WIDTH, HEIGHT = 800, 800
ROWS, COLS = 3, 3

BOARD_PADDING_Y = HEIGHT // 8
BOARD_PADDING_X = WIDTH // 8

BOARD_HEIGHT = HEIGHT - 2 * BOARD_PADDING_Y
BOARD_WIDTH = WIDTH - 2 * BOARD_PADDING_X

SQUARE_SIZE = BOARD_HEIGHT // ROWS

#rgb colors
WHITE = (255,255,255)
BLACK = (0,0,0)
GREEN = (0,255,0)